// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToCSV(arg1) {
  return window['go']['main']['App']['ExportToCSV'](arg1);
}

export function ExportToSheets(arg1) {
  return window['go']['main']['App']['ExportToSheets'](arg1);
}

export function StartScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3);
}
