// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {parser} from '../models';

export function ExportToCSV(arg1:Array<main.Result>):Promise<void>;

export function ExportToSheets(arg1:Array<main.Result>):Promise<void>;

export function StartScan(arg1:string,arg2:boolean,arg3:boolean):Promise<Array<parser.Prospect>>;
